// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQYK4v_BGWYFKwsCGVV9Gqu5Ztu9v3fF8',
    appId: '1:462372905842:web:5ce776b8d480e70131f3eb',
    messagingSenderId: '462372905842',
    projectId: 'medicore-eefb6',
    authDomain: 'medicore-eefb6.firebaseapp.com',
    storageBucket: 'medicore-eefb6.firebasestorage.app',
    measurementId: 'G-RWSRQ8XFLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs1qI3EJm4ik_4P0KPjwZZ1B9WdUDnUCI',
    appId: '1:462372905842:android:5634717508e5d4b731f3eb',
    messagingSenderId: '462372905842',
    projectId: 'medicore-eefb6',
    storageBucket: 'medicore-eefb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy0J7kTKnyyuTOuugVyaGgB1XEfF1S-hw',
    appId: '1:462372905842:ios:517bbf095a5d682f31f3eb',
    messagingSenderId: '462372905842',
    projectId: 'medicore-eefb6',
    storageBucket: 'medicore-eefb6.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy0J7kTKnyyuTOuugVyaGgB1XEfF1S-hw',
    appId: '1:462372905842:ios:517bbf095a5d682f31f3eb',
    messagingSenderId: '462372905842',
    projectId: 'medicore-eefb6',
    storageBucket: 'medicore-eefb6.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQYK4v_BGWYFKwsCGVV9Gqu5Ztu9v3fF8',
    appId: '1:462372905842:web:c38ac1946de7b34631f3eb',
    messagingSenderId: '462372905842',
    projectId: 'medicore-eefb6',
    authDomain: 'medicore-eefb6.firebaseapp.com',
    storageBucket: 'medicore-eefb6.firebasestorage.app',
    measurementId: 'G-FMYR1KGHND',
  );
}
